# Source: keto/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-keto
  namespace: default
  labels:
    app.kubernetes.io/name: keto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keto
      app.kubernetes.io/instance: test-keto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keto
        app.kubernetes.io/instance: test-keto
    spec:
      serviceAccountName: test-keto
      automountServiceAccountToken: true
      volumes:
        - name: keto-config-volume
          configMap:
            name: keto-config
      initContainers:
        - name: keto-automigrate
          image: "oryd/keto:v0.8.0-alpha.2"
          imagePullPolicy: IfNotPresent
          command: ["keto"]
          args: ["migrate", "up", "-y", "--config", "/etc/config/keto.yaml"]
          volumeMounts:
            - name: keto-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: keto-secret
                  key: dsn
      containers:
        - name: keto
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100
          image: "oryd/keto:v0.8.0-alpha.2"
          imagePullPolicy: IfNotPresent
          command: ["keto"]
          args: ["serve", "--config", "/etc/config/keto.yaml"]
          volumeMounts:
            - name: keto-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: keto-secret
                  key: dsn
          ports:
            - name: keto-write-api
              containerPort: 4457
              protocol: TCP
            - name: keto-read-api
              containerPort: 4456
              protocol: TCP
            - name: http-metrics
              containerPort: 4468
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: keto-write-api
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: keto-write-api
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
